fotoShoutPortal/Controllers/EventWebsiteController.cs
using FotoShoutData.Models;
using FotoShoutUtils;
using FotoShoutUtils.Utils;
using log4net;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FotoShoutPortal.Controllers {
    [Authorize]
    public class EventWebsiteController : AuthenticatedController {
        readonly static ILog _logger = LogManager.GetLogger(typeof(EventWebsiteController));
        //
        // GET: /EventWebsite/
        public ActionResult Index() {
            return View(fsWebService.GetEventWebsites());
        }

        //
        // GET: /EventWebsite/Create
        public ActionResult Create() {
            return Modify(0);
        }

        //
        // POST: /EventWebsite/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WebsiteTDO tdo) {
            ValidateWebsiteTDO(tdo);

            if (ModelState.IsValid) {
                try {
                    var website = this.WebsiteTDO2Website(tdo);
                    if (fsWebService.CreateEventWebsite(website) != null)
                        return RedirectToAction("Index");
                    else {
                        this.AddModelError(string.Format(Errors.ERROR_EVENTSPONSOR_CREATE_UNEXPECTED, website.WebsiteName), _logger);
                    }
                }
                catch (Exception ex) {
                    this.AddModelError(ex.Message, _logger, ex);
                }
            }
            else {
                this.AddModelError(ModelState.Values.SelectMany(v => v.Errors).ToList(), _logger);
            }

            return View("Modify", tdo);
        }

        //
        // GET: /EventWebsite/Edit/5
        public ActionResult Edit(int id) {
            return Modify(id);
        }

        //
        // POST: /EventWebsite/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WebsiteTDO tdo) {
            ValidateWebsiteTDO(tdo);

            if (ModelState.IsValid) {
                try {
                    var website = this.WebsiteTDO2Website(tdo);
                    fsWebService.UpdateEventWebsite(website);
                    return RedirectToAction("Index");
                }
                catch (Exception ex) {
                    this.AddModelError(ex.Message, _logger, ex);
                }
            }
            else {
                this.AddModelError(ModelState.Values.SelectMany(v => v.Errors).ToList(), _logger);
            }

            return View("Modify", tdo);
        }

        //
        // GET: /EventWebsite/Delete/5
        public ActionResult Delete(int id = 0) {
            Website website = fsWebService.GetEventWebsite(id);
            return PartialView("_DeleteConfirmation", website);
        }

        //
        // POST: /EventWebsite/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            try {
                Website website = fsWebService.DeleteEventWebsite(id);
                if (website == null)
                    this.AddModelError(string.Format(Errors.ERROR_EVENTSPONSOR_DELETE, id), _logger);
            }
            catch (Exception ex) {
                this.AddModelError(ex.Message, _logger, ex);
            }

            return RedirectToAction("Index");
        }

        #region Helpers
        private ActionResult Modify(int id) {
            try {
                Website website = (id != 0) ? fsWebService.GetEventWebsite(id) : null;
                return ((website != null) ? View("Modify", this.Website2WebsiteTDO(website)) : View("Modify"));
            }
            catch (Exception ex) {
                FotoShoutUtils.Log.LogManager.Error(_logger, ex.ToString());
                return HttpNotFound(ex.Message);
            }
        }

        private WebsiteTDO Website2WebsiteTDO(Website website) {
            WebsiteTDO tdo = new WebsiteTDO {
                WebsiteId = website.WebsiteId,
                WebsiteName = website.WebsiteName,
                HeaderUrl = website.HeaderUrl,
                FooterUrl = website.FooterUrl,
                TopInfoBlockUrl = website.TopInfoBlockUrl,
                BottomInfoBlockUrl = website.BottomInfoBlockUrl,
                HeaderImage = website.HeaderImage,
                FooterImage = website.FooterImage,
                TopInfoBlockImage = website.TopInfoBlockImage,
                BottomInfoBlockImage = website.BottomInfoBlockImage
            };

            return tdo;
        }
        
        private Website WebsiteTDO2Website(WebsiteTDO tdo) {
            Website website = new Website {
                WebsiteId = tdo.WebsiteId,
                WebsiteName = tdo.WebsiteName,
                HeaderUrl = tdo.HeaderUrl,
                FooterUrl = tdo.FooterUrl,
                TopInfoBlockUrl = tdo.TopInfoBlockUrl,
                BottomInfoBlockUrl = tdo.BottomInfoBlockUrl,
                HeaderImage = tdo.HeaderImage,
                FooterImage = tdo.FooterImage,
                TopInfoBlockImage = tdo.TopInfoBlockImage,
                BottomInfoBlockImage = tdo.BottomInfoBlockImage
            };

            var uploadDir = "~/uploads";
            var uploadPath = Server.MapPath(uploadDir);
            var imagePath = "";
            DirectoryInfo dirInfo = new DirectoryInfo(uploadPath);
            if (!dirInfo.Exists) {
                Directory.CreateDirectory(uploadPath);
            }

            if (tdo.HeaderFile != null) {
                var websiteHeaderImage = Path.Combine(uploadDir, tdo.HeaderFile.FileName).Replace('\\', '/');
                if (websiteHeaderImage != website.HeaderImage) {
                    website.HeaderImage = websiteHeaderImage;
                    imagePath = Path.Combine(uploadPath, tdo.HeaderFile.FileName);
                    tdo.HeaderFile.SaveAs(imagePath);
                }
            }

            if (tdo.FooterFile != null) {
                var websiteFooterImage = Path.Combine(uploadDir, tdo.FooterFile.FileName).Replace('\\', '/');
                if (websiteFooterImage != website.FooterImage) {
                    website.FooterImage = websiteFooterImage;
                    imagePath = Path.Combine(uploadPath, tdo.FooterFile.FileName);
                    tdo.FooterFile.SaveAs(imagePath);
                }
            }

            if (tdo.TopInfoBlockFile != null) {
                var websiteTopInfoBlockImage = Path.Combine(uploadDir, tdo.TopInfoBlockFile.FileName).Replace('\\', '/');
                if (websiteTopInfoBlockImage != website.TopInfoBlockImage) {
                    website.TopInfoBlockImage = websiteTopInfoBlockImage;
                    imagePath = Path.Combine(uploadPath, tdo.TopInfoBlockFile.FileName);
                    tdo.TopInfoBlockFile.SaveAs(imagePath);
                }
            }

            if (tdo.BottomInfoBlockFile != null) {
                var websiteBottomInfoBlockImage = Path.Combine(uploadDir, tdo.BottomInfoBlockFile.FileName).Replace('\\', '/');
                if (websiteBottomInfoBlockImage != website.BottomInfoBlockImage) {
                    website.BottomInfoBlockImage = websiteBottomInfoBlockImage;
                    imagePath = Path.Combine(uploadPath, tdo.BottomInfoBlockFile.FileName);
                    tdo.BottomInfoBlockFile.SaveAs(imagePath);
                }
            }

            return website;
        }

        private void ValidateWebsiteTDO(WebsiteTDO tdo) {
            var imageTypes = ImageUtils.GetImageTypes();
            if (tdo.HeaderFile != null) {
                if (!imageTypes.Contains(tdo.HeaderFile.ContentType)) {
                    ModelState.AddModelError("HeaderFile", "Please choose either a JPG or PNG image for the 'Header Image' field.");
                    return;
                }
            }

            if (tdo.FooterFile != null) {
                if (!imageTypes.Contains(tdo.FooterFile.ContentType)) {
                    ModelState.AddModelError("FooterFile", "Please choose either a JPG or PNG image for the 'Footer Image' field.");
                    return;
                }
            }

            if (tdo.TopInfoBlockFile != null) {
                if (!imageTypes.Contains(tdo.TopInfoBlockFile.ContentType)) {
                    ModelState.AddModelError("TopInfoBlockFile", "Please choose either a JPG or PNG image for the 'Top Block Image' field.");
                    return;
                }
            }

            if (tdo.BottomInfoBlockFile != null) {
                if (!imageTypes.Contains(tdo.BottomInfoBlockFile.ContentType)) {
                    ModelState.AddModelError("BottomInfoBlockFile", "Please choose either a JPG or PNG image for the 'Bottom Block Image' field.");
                    return;
                }
            }
        }

        #endregion // Helpers
    }
}

fotoShoutPortal/Views/EventWebsite/Index.cshtml
@model IEnumerable<FotoShoutData.Models.Website>

@{
    ViewBag.Title = "Event Websites";
    ViewBag.AppName = "fotoShout";
}

@Html.Partial("~/Views/Preferences/_PreferCommands.cshtml", "EventWebsites")

<section id="main-panel">
    <div class="div-list">
        <h2>@ViewBag.Title</h2>
        <p>
            @Html.ActionLink("New Event Website", "Create")
        </p>
        <fieldset>
            <legend>@ViewBag.Title</legend>
            <table>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.WebsiteName)
                    </th>
                    <th></th>
                </tr>

            @foreach (var item in Model) {
                <tr class="row-item">
                    <td>
                        @Html.DisplayFor(modelItem => item.WebsiteName)
                    </td>
                    <td>
                        <p class="hidden">
                            @Html.ActionLink(" ", "Edit", new { id = item.WebsiteId }, new { @class = "linkEdit" })
                            @Html.ActionLink(" ", "Delete", new { id = item.WebsiteId }, new { @class = "linkDelete" })
                        </p>
                    </td>
                </tr>
            }

            </table>
        </fieldset>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="@Url.Content("~/Scripts/inc/eventwebsites.js?1.3.0.10")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var tabCtrl = new TabControl('@Request.ApplicationPath');
            var initializer = new Initializer(tabCtrl, "preferences");
            var evWebsites = new EventWebsites();
        });
    </script>
}

fotoShoutPortal/Views/EventWebsite/Modify.cshtml
@model FotoShoutData.Models.WebsiteTDO

@{
    var isEdit = (Model != null && Model.WebsiteId != 0);
    var websiteHeaderImage = (isEdit && Model.HeaderImage != null) ? Model.HeaderImage.LastIndexOf('/') != -1 ? Model.HeaderImage.Substring(Model.HeaderImage.LastIndexOf('/') + 1) : Model.HeaderImage : "";
    var websiteTopInfoBlockImage = (isEdit && Model.TopInfoBlockImage != null) ? Model.TopInfoBlockImage.LastIndexOf('/') != -1 ? Model.TopInfoBlockImage.Substring(Model.TopInfoBlockImage.LastIndexOf('/') + 1) : Model.TopInfoBlockImage : "";
    var websiteBottomInfoBlockImage = (isEdit && Model.BottomInfoBlockImage != null) ? Model.BottomInfoBlockImage.LastIndexOf('/') != -1 ? Model.BottomInfoBlockImage.Substring(Model.BottomInfoBlockImage.LastIndexOf('/') + 1) : Model.BottomInfoBlockImage : "";
    var websiteFooterImage = (isEdit && Model.FooterImage != null) ? Model.FooterImage.LastIndexOf('/') != -1 ? Model.FooterImage.Substring(Model.FooterImage.LastIndexOf('/') + 1) : Model.FooterImage : "";

    ViewBag.Title = isEdit ? "Update Event Client" : "Create Event Client";
    ViewBag.AppName = "fotoShout";
}

@using (Html.BeginForm(isEdit ? "Edit" : "Create", "EventWebsite", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    @Html.Partial("~/Views/Preferences/_PreferCommands.cshtml", "EventWebsites")

    <section id="main-panel">
        <div class="div-form-detail">
            <h2>@ViewBag.Title</h2>
            <fieldset class="form-fields">
                <legend>Event Client Info</legend>

                @if (isEdit)
                {
                    @Html.HiddenFor(model => model.WebsiteId);
                }

                <div>
                    <span class="field-label">@Html.LabelFor(model => model.WebsiteName)<span>&nbsp;*</span></span>
                    @Html.EditorFor(model => model.WebsiteName)
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.HeaderFile)</span>
                    @Html.TextBoxFor(model => model.HeaderFile, new { type = "file" })
                    @if (websiteHeaderImage.Length != 0)
                    {
                        @Html.HiddenFor(model => model.HeaderImage);
                        <span class="field-label"></span>
                        <span class="field-current-value">Current Value: @websiteHeaderImage</span>
                    }
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.HeaderUrl)</span>
                    @Html.EditorFor(model => model.HeaderUrl)
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.TopInfoBlockFile)</span>
                    @Html.TextBoxFor(model => model.TopInfoBlockFile, new { type = "file" })
                    @if (websiteTopInfoBlockImage.Length != 0)
                    {
                        @Html.HiddenFor(model => model.TopInfoBlockImage);
                        <span class="field-label"></span>
                        <span class="field-current-value">Current Value: @websiteTopInfoBlockImage</span>
                    }
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.TopInfoBlockUrl)</span>
                    @Html.EditorFor(model => model.TopInfoBlockUrl)
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.BottomInfoBlockFile)</span>
                    @Html.TextBoxFor(model => model.BottomInfoBlockFile, new { type = "file" })
                    @if (websiteBottomInfoBlockImage.Length != 0)
                    {
                        @Html.HiddenFor(model => model.BottomInfoBlockImage);
                        <span class="field-label"></span>
                        <span class="field-current-value">Current Value: @websiteBottomInfoBlockImage</span>
                    }
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.BottomInfoBlockUrl)</span>
                    @Html.EditorFor(model => model.BottomInfoBlockUrl)
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.FooterFile)</span>
                    @Html.TextBoxFor(model => model.FooterFile, new { type = "file" })
                    @if (websiteFooterImage.Length != 0)
                    {
                        @Html.HiddenFor(model => model.FooterImage);
                        <span class="field-label"></span>
                        <span class="field-current-value">Current Value: @websiteFooterImage</span>
                    }
                </div>
                <div>
                    <span class="field-label">@Html.LabelFor(model => model.FooterUrl)</span>
                    @Html.EditorFor(model => model.FooterUrl)
                </div>

                @Html.Partial("~/Views/Shared/_FormButtons.cshtml", "EventWebsite")
            </fieldset>
        </div>
    </section>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="@Url.Content("~/Scripts/inc/eventwebsites.js?1.3.0.10")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var tabCtrl = new TabControl('@Request.ApplicationPath');
            var initializer = new Initializer(tabCtrl, "preferences");
            var evWebsites = new EventWebsites();
            window.App.init($('form'), 1);
        });
    </script>
}

fotoShoutPortal/Views/EventWebsite/_DeleteConfirmation.cshtml
@model FotoShoutData.Models.Website

<div><h6>Are you sure you want to delete the '@Model.WebsiteName' event client?</h6></div>
@using (Html.BeginForm("Delete", "EventWebsite", FormMethod.Post, new { id = "deleteForm" })) {
    @Html.AntiForgeryToken()
}